#!/bin/bash
# rename_tags.sh
# Renames old CZ-based tag slugs to new EN-based tag slugs in faq_tags.csv and faq.csv
# Uses a hardcoded mapping derived from the original CZ tags.

DIR="$(cd "$(dirname "$0")" && pwd)"
FAQ_FILE="$DIR/faq.csv"

# Mapping: old_cz_tag -> new_en_tag
# Order matters: longer/more-specific patterns first to avoid partial matches
declare -a MAPPINGS=(
    "princip-hry|game-principle"
    "herní-prvky|game-components"
    "dobírací-balíčky|draw-decks"
    "karty-na-ruce|hand-cards"
    "karty-příběhu|story-cards"
    "jsem-epic|i-am-epic"
    "na-stole|on-table"
    "vítězné-body|victory-points"
    "symboly-karet|card-symbols"
    "míchání-balíčků|deck-mixing"
    "příprava-hry|game-setup"
    "začínající-hráč|starting-player"
    "stavba-mapy|map-building"
    "speciální-pole|special-tiles"
    "dostupnost-polí|tile-accessibility"
    "umístění-příšer|monster-placement"
    "volba-startu|starting-position"
    "počáteční-zbraně|initial-weapons"
    "počáteční-karty|initial-cards"
    "veřejná-nabídka|public-offer"
    "tah-hráče|player-turn"
    "fáze-tahu|turn-phases"
    "dobrání-zbraní|drawing-weapons"
    "plnění-úkolů|quest-completion"
    "doplňování-příšer|monster-replenishment"
    "výměna-úkolu|quest-exchange"
    "úkol-trofej|trophy-quest"
    "úkol-formace|formation-quest"
    "úkol-bariéra|barrier-quest"
    "stůj-mezi|stand-between"
    "stůj-v-řadě|stand-in-line"
    "chraň-vesnici|protect-village"
    "zažeň-ke-skále|chase-to-rock"
    "kouzlo-tvrdosti|hardness-spell"
    "kouzlo-záměny|swap-spell"
    "kouzlo-vábení|lure-spell"
    "kouzlo-vzteku|rage-spell"
    "kouzlo-krádeže|theft-spell"
    "kouzlo-létání|flying-spell"
    "opakované-hry|repeated-games"
    "trestné-body|penalty-points"
    "pole-start|start-tile"
    "pole-vesnice|village-tile"
    "pole-věž|tower-tile"
    "pole-teleport|teleport-tile"
    "pole-skála|rock-tile"
    "pole-hrad|castle-tile"
    "povolání|profession"
    "vítězství|victory"
    "příšery|monsters"
    "trofeje|trophies"
    "předměty|items"
    "odpočinek|rest"
    "vybavení|equipment"
    "figurky|figurines"
    "nápovědy|help-cards"
    "zbraně|weapons"
    "zvíře|beast"
    "nemrtvý|undead"
    "člověk|human"
    "démon|demon"
    "pohyb|movement"
    "úkoly|quests"
    "kouzla|spells"
    "turnaj|tournament"
    "dohrávání|finishing-round"
    "palice|mace"
    "bomba|bomb"
    "skóre|score"
    "kopí|spear"
    "mapa|map"
    "hory|mountains"
    "meč|sword"
    "luk|bow"
    "boj|combat"
)

# Build a sed expression - process longer patterns first (already ordered above)
SED_EXPR=""
for mapping in "${MAPPINGS[@]}"; do
    old="${mapping%%|*}"
    new="${mapping##*|}"
    # Use word-boundary-like matching with comma/pipe delimiters
    SED_EXPR="${SED_EXPR}s/${old}/${new}/g;"
done

echo "Processing $FAQ_FILE ..."
sed -i "$SED_EXPR" "$FAQ_FILE"

echo "Done! All CZ tags in faq.csv have been renamed to EN."
echo ""
echo "Verifying - first 5 lines of faq.csv:"
head -5 "$FAQ_FILE"

